trigger:
  branches:
    include:
      - main

variables:
  TF_VERSION: '1.6.0'
  TF_WORKING_DIR: '$(System.DefaultWorkingDirectory)'
  AWS_REGION: 'us-east-2'

stages:

# ===== CI Stage =====
- stage: Build
  displayName: "Terraform Build & Publish Artifact"
  jobs:
  - job: TerraformBuild
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      - group: aws-credentials        # AWS keys
      - group: azure-ssh-credentials  # AZURE_SSH_PUB_KEY
      - group: azure-credentials      # Optional Azure variables if needed
    steps:
      - checkout: self
        clean: true

      # Install Terraform
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: '$(TF_VERSION)'

      # Terraform Init, Validate & Plan (AWS + Azure) using Azure OIDC authentication
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'azure-spn'   # must match service connection name
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            cd $(TF_WORKING_DIR)

            # Initialize Terraform (downloads providers)
            terraform init

            # Fix permissions for all provider binaries
            find .terraform/providers/ -type f -name "terraform-provider-*" -exec chmod +x {} \;

            # Import existing Azure Resource Group if it exists
            if az group show --name multiCloudRG &> /dev/null; then
              echo "Resource group exists, importing into Terraform state..."
              terraform import azurerm_resource_group.rg /subscriptions/$(AZURE_SUBSCRIPTION_ID)/resourceGroups/multiCloudRG
            else
              echo "Resource group does not exist, Terraform will create it."
            fi

            # Validate Terraform
            terraform validate

            # Terraform plan with variables
            terraform plan \
              -var "azure_ssh_pub_key=$(AZURE_SSH_PUB_KEY)" \
              -var "azure_subscription_id=$(AZURE_SUBSCRIPTION_ID)" \
              -out=tfplan
        env:
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

      # Publish Terraform artifact
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(TF_WORKING_DIR)'
          artifact: 'terraform-iac'
          publishLocation: 'pipeline'

# ===== CD Stage =====
- stage: Deploy
  displayName: "Terraform Apply (AWS + Azure)"
  dependsOn: Build
  jobs:
  - job: TerraformApply
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      - group: aws-credentials
      - group: azure-ssh-credentials
    steps:
      - download: current
        artifact: terraform-iac

      # Install Terraform
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: '$(TF_VERSION)'

      # Terraform Apply (AWS + Azure) using Azure OIDC authentication
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'azure-spn'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            cd $(Pipeline.Workspace)/terraform-iac

            # Initialize Terraform (downloads providers)
            terraform init

            # Fix provider binary permissions
            find .terraform/providers/ -type f -name "terraform-provider-*" -exec chmod +x {} \;

            # Apply the saved plan
            terraform apply -auto-approve tfplan
        env:
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

      # Export Terraform outputs
      - script: |
          cd $(Pipeline.Workspace)/terraform-iac
          terraform output -json > terraform-outputs.json
        displayName: "Export Terraform Outputs"

      # Publish outputs
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Pipeline.Workspace)/terraform-iac/terraform-outputs.json'
          artifact: 'TerraformOutputs'
          publishLocation: 'pipeline'


