trigger:
  branches:
    include:
      - main

variables:
  TF_VERSION: '1.6.0'
  TF_WORKING_DIR: '$(System.DefaultWorkingDirectory)'
  AWS_REGION: 'us-east-2'

stages:

# ===== CI Stage =====
- stage: Build
  displayName: "Terraform Build & Publish Artifact"
  jobs:
  - job: TerraformBuild
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      - group: aws-credentials   # AWS keys stored in Azure DevOps Variable Group
    steps:
      # Checkout repo
      - checkout: self

      # Fix permissions for Terraform AWS provider
      - script: |
          cd $(TF_WORKING_DIR)
          chmod +x .terraform/providers/registry.terraform.io/hashicorp/aws/*/linux_amd64/terraform-provider-aws* || true
        displayName: "Fix AWS provider permissions"

      # Install Terraform
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: '$(TF_VERSION)'

      # Azure Login using service connection 'azure-spn'
      - task: AzureCLI@2
        inputs:
          azureSubscription: "azure-spn"
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            echo "Logged in to Azure CLI"

      # Terraform Init & Validate
      - script: |
          cd $(TF_WORKING_DIR)
          terraform init
          terraform validate
        displayName: "Terraform Init & Validate"
        env:
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

      # Terraform Plan
      - script: |
          cd $(TF_WORKING_DIR)
          terraform plan -var-file="terraform.tfvars" -out=tfplan
        displayName: "Terraform Plan"
        env:
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

      # Publish Terraform code + plan as artifact
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(TF_WORKING_DIR)'
          artifact: 'terraform-iac'
          publishLocation: 'pipeline'

# ===== CD Stage =====
- stage: Deploy
  displayName: "Terraform Apply (AWS + Azure)"
  dependsOn: Build
  jobs:
  - job: TerraformApply
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      - group: aws-credentials   # AWS keys for deploy stage
    steps:
      # Download artifact from Build stage
      - download: current
        artifact: terraform-iac

      # Fix permissions for Terraform AWS provider
      - script: |
          cd $(Pipeline.Workspace)/terraform-iac
          chmod +x .terraform/providers/registry.terraform.io/hashicorp/aws/*/linux_amd64/terraform-provider-aws* || true
        displayName: "Fix AWS provider permissions"

      # Install Terraform
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: '$(TF_VERSION)'

      # Azure Login using service connection 'azure-spn'
      - task: AzureCLI@2
        inputs:
          azureSubscription: "azure-spn"
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            echo "Logged in to Azure CLI"

      # Terraform Apply using saved plan
      - script: |
          cd $(Pipeline.Workspace)/terraform-iac
          terraform init
          terraform apply -auto-approve tfplan
        displayName: "Terraform Apply"
        env:
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

      # Export Terraform outputs
      - script: |
          cd $(Pipeline.Workspace)/terraform-iac
          terraform output -json > terraform-outputs.json
        displayName: "Export Terraform Outputs"

      # Publish outputs as artifact
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Pipeline.Workspace)/terraform-iac/terraform-outputs.json'
          artifact: 'TerraformOutputs'
          publishLocation: 'pipeline'