trigger:
  branches:
    include:
      - main

variables:
  TF_VERSION: "1.5.0"
  AWS_DEFAULT_REGION: "us-east-2"

stages:
  - stage: BuildAndDeploy
    displayName: "Terraform Multi-Cloud Build & Deploy"
    jobs:
      - job: Terraform
        displayName: "Deploy AWS EC2 + Azure VM"
        pool:
          vmImage: "ubuntu-latest"

        steps:
          # 1. Checkout repo
          - task: Checkout@2

          # 2. Install Terraform
          - task: HashiCorpTerraformInstaller@1
            inputs:
              terraformVersion: $(TF_VERSION)

          # 3. Azure Login
          - task: AzureCLI@2
            inputs:
              azureSubscription: "AzureServiceConnection"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Logged in to Azure CLI"

          # 4. Configure AWS credentials from pipeline variables
          - script: |
              echo "Setting AWS environment variables"
              echo "##vso[task.setvariable variable=AWS_ACCESS_KEY_ID]$(AWS_ACCESS_KEY_ID)"
              echo "##vso[task.setvariable variable=AWS_SECRET_ACCESS_KEY]$(AWS_SECRET_ACCESS_KEY)"
              export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
              export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
              export AWS_DEFAULT_REGION=$(AWS_DEFAULT_REGION)
            displayName: "Configure AWS Credentials"

          # 5. Terraform Init
          - script: |
              terraform init
            displayName: "Terraform Init"

          # 6. Terraform Plan
          - script: |
              terraform plan -out=tfplan
            displayName: "Terraform Plan"

          # 7. Terraform Apply
          - script: |
              terraform apply -auto-approve tfplan
            displayName: "Terraform Apply"

          # 8. Capture Terraform outputs to file
          - script: |
              terraform output -json > terraform-outputs.json
            displayName: "Export Terraform Outputs"

          # 9. Publish outputs as pipeline artifact
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: 'terraform-outputs.json'
              artifactName: 'TerraformOutputs'
              publishLocation: 'pipeline'